// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (migrate, db push) cần dùng Session pooler (port 5432) hoặc Direct connection
    // KHÔNG dùng Transaction pooler (port 6543) vì nó không hỗ trợ DDL lâu
    url: process.env["DIRECT_URL"],
  },
});
